scrape_configs:
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']